postprocessor_pipeline: # set by postprocessor_pipeline_name
  # # Fill holes in the map with inpainting.
  # - name: inpaint
  #   type: gridMapCv/InpaintFilter
  #   params:
  #     input_layer: elevation
  #     output_layer: elevation_inpainted_temp
  #     radius: 0.05

  # # Fill holes in the map with 0.0 value.
  # - name: inpaint
  #   type: gridMapFilters/FillholeFilter
  #   params:
  #     input_layer: elevation
  #     output_layer: elevation_inpainted_temp
  #     fill_value: 0.0

  - name: median
    type: gridMapFilters/MedianFillFilter
    params:
      input_layer: elevation
      output_layer: elevation_inpainted_temp
      fill_hole_radius: 5.0 # in m. 
      filter_existing_values: false # Default is false. If enabled it also does a median computation for existing values. 
      existing_value_radius: 0.2 # in m. Note that this option only has an effect if filter_existing_values is set true. 
      num_erode_dilation_iterations: 4
      fill_mask_layer: elevation # A layer that is used to compute which areas to fill. If not present in the input it is automatically computed. 
      debug: false # If enabled, the additional debug_infill_mask_layer is published. 
      debug_infill_mask_layer: infill_mask # Layer used to visualize the intermediate, sparse-outlier removed fill mask. Only published if debug is enabled.

  - name: mean_in_radius
    type: gridMapFilters/MeanInRadiusFilter
    params:
      input_layer: elevation_inpainted_temp
      output_layer: elevation_inpainted
      radius: 0.05

  # Compute Surface normals
  - name: surface_normals
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation_inpainted
      output_layers_prefix: normal_
      radius: 0.3
      normal_vector_positive_axis: z
      parallelization_enabled: true
      thread_number: -1

  # Compute surface normals.
  - name: surface_normals_noblur
    type: gridMapFilters/NormalVectorsFilter
    params:
      input_layer: elevation_inpainted
      output_layers_prefix: normal_noblur_
      radius: 0.1
      normal_vector_positive_axis: z

  #  Delete layers that are not needed to reduce bandwidth
  #  - name: delete_original_layers
  #    type: gridMapFilters/DeletionFilter
  #    params:
  #      layers: [lowest_scan_point,sensor_x_at_lowest_scan, sensor_y_at_lowest_scan, sensor_z_at_lowest_scan] # List of layers.
